### ISSUE TITLE
نیاز به خروجی تاریخ با فرمت "۱۰ فروردین ۱۳۹۶-۱۷:۳۰"

### ISSUE THREAD

**Issue by Mehrdad-Davoudi** [VahidN/DNTPersianUtils.Core#1]
اگر امکان داره خروجی به فرمت "نیاز به خروجی تاریخ با فرمت "۱۰ فروردین ۱۳۹۶-۱۷:۳۰" رو هم به پروژه اضافه کنید.
با تشکر

**Comment by VahidN** [comment]
<div dir="rtl">
dt.ToLongPersianDateTimeString()  يك چنين خروجي فرضي دارد «‫21 دی 1395، 10:20:02 ق.ظ»

براي ساير حالات سفارشي از اين روش استفاده كنيد كه از فرهنگ سفارشي و اصلاح شده‌ي فارسي استفاده مي‌كند:
dt.ToPersianDateTimeString("dd MMMM yyyy - HH:mm")
با اين خروجي فرضي: «21 دی 1395 - 10:20»

**Comment by Mehrdad-Davoudi** [comment]
ولی خروجی با اعداد انگلیسی هست. برای خروجی با اعداد فارسی چه باید کرد؟

**Comment by Mehrdad-Davoudi** [comment]
dt.ToPersianDateTimeString("dd MMMM yyyy - HH:mm").ToPersianNumbers()
با این روش مشکل حل شد. ممنون از راهنمایی و زحمت شما
