### ISSUE TITLE
تاریخ قمری

### ISSUE THREAD

**Issue by ghost1372** [VahidN/DNTPersianUtils.Core#10]
<div dir="rtl">

سلام لطفا تاریخ دقیق قمری رو هم اضافه کنید

**Comment by VahidN** [comment]
سلام؛ ايده‌اي در اين مورد داريد؟ فرمول زير وابسته‌است به تنظيمات ويندوز و دقيق نيست
https://www.dotnettips.info/post/2534

**Comment by ghost1372** [comment]
بله بدلیل اختلاف روزهای ماه های قمری با شمسی و میلادی این اختلاف روز پیش میاد، البته من تاریخ قمری رو به این صورت دریافت میکنم
`HijriCalendar hc = new HijriCalendar();`
به کمک متد HijriAdjustment 
میشه اختلاف روز رو از بازه -2 تا 2 تنظیم کرد تا حدی میشه این مشکل رو با کمک این روش حلش کرد
اما کاملترین روشی که دیدم داخل تقویم فارسی اندروید هستش که اونجوری که توی کدهاش یه چرخی زدم اطلاعات روز و ماه و سال چندین سال رو بصورت دقیق گرداوری کردن و با تجزیه و تحلیل اون ها تاریخ دقیق رو حساب میکنن
اینجارو یه بررسی کنید
https://github.com/ebraminio/DroidPersianCalendar/blob/master/PersianCalendar/src/main/java/calendar/IslamicDateConverter.java

**Comment by VahidN** [comment]
Added via #https://github.com/VahidN/DNTPersianUtils.Core/commit/a0b0a2e7d57543a3cd60e57e904ffa9661dd7300
