### ISSUE TITLE
دریافت تاریخ و محاسبه اولین و آخرین روز

### ISSUE THREAD

**Issue by ahmad7485** [VahidN/DNTPersianUtils.Core#16]
<div dir="rtl">

در راستای تکمیل این کتابخانه درخواست مبنی بر اینکه بتوان متدی اضافه شود که تاریخی را دریافت کرده اولین روز هفته و اخرین روز هفته تاریخ مد نظر را در خروجی تحویل داده و همچنین متد دیگری برای اولین روز و اخرین روز ماه با تشکر

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/DNTPersianUtils.Core/commit/4378c8d25e32b9d45a57484fe0da246be4e176ae
