### ISSUE TITLE
کار نکردن ToPersianNumbers() در دات نت کر ۳

### ISSUE THREAD

**Issue by webiox** [VahidN/DNTPersianUtils.Core#18]
# Summary of the issue

سلام

ظاهرا 
ToPersianNumbers()
توی دات نت کر نسخه‌ی ۳ کار نمیکنه و احتمالا تغییراتی توی 
CultureInfo.InvariantCulture
اعمال شده که باعث میشه درست کار نکنه

## Example code/Steps to reproduce:

```
MyNumber.ToPersianNumbers();

**Comment by VahidN** [comment]
<div dir="rtl">

CultureInfo.InvariantCulture فقط به اين معنا است كه بر اساس تنظيمات سيستم عامل فعلي، خروجي عددي رو تغيير نده. يعني اگر قرار هست 12.3 چاپ شود، 12/3 يا هيچ حالت ديگري چاپ نخواهد شد؛ فقط 12.3 چاپ مي‌شود.
در كل متد ToPersianNumbers هيچ وابستگي خاصي به شماره نگارش دات نت شما ندارد و مشكل كار شما قطعا جاي ديگري هست.

**Comment by webiox** [comment]
ممنون 👍

**Comment by VahidN** [comment]
<div dir="rtl">

يك نمونه مثال با دات نت Core 3 كه مشكلي ندارد

[TestDNTPersianUtilsCore3.zip](https://github.com/VahidN/DNTPersianUtils.Core/files/3751820/TestDNTPersianUtilsCore3.zip)
![core3](https://user-images.githubusercontent.com/766010/67222405-20f94b80-f43a-11e9-93a2-6ee9e7a66e16.png)
