### ISSUE TITLE
Friendly Persian Date can't remove 'dddd yyyy MMM'

### ISSUE THREAD

**Issue by mohammad68a** [VahidN/DNTPersianUtils.Core#19]
درصورتیکه بخواهیم در متد 
```
.ToFriendlyPersianDateTextify()
```
تاریخ دقیق درج نشود بطور مثال در خروجی 
‫۱۰ روز قبل، سه شنبه ۲۱ دی ۱۳۹۵، ساعت ۱۰:۲۰
مقدار
سه شنبه ۲۱ دی ۱۳۹۵
نشان داده نشود و خروجی به شکل
‫۱۰ روز قبل، ساعت ۱۰:۲۰

 در اکستنشن متد مورد نظر هیچ آرگومانی برای اینکار وجود ندارد

**Comment by VahidN** [comment]
Use [includePersianDate](https://github.com/VahidN/DNTPersianUtils.Core/commit/981fbe34ef84b4f365d325d8a466b5cbcd5de8ca#diff-0e863dd9b974d6111428f74f159f80d1R89) parameter.
