### ISSUE TITLE
Optional parameters must filled when use methods!

### ISSUE THREAD

**Issue by mohammad68a** [VahidN/DNTPersianUtils.Core#20]
When we use methods which contain optional parameters they need to fill like as required parameters! but shouldn't be that way!

 
![Call one method](https://user-images.githubusercontent.com/25847545/70846115-73b81800-1e6b-11ea-9919-0c886696fb5e.PNG)

**Comment by VahidN** [comment]
Do you get an error from the compiler? Or it's just a hint form an addon/extension? Can you compile your code? Also delete all of your `bin` and `obj` folders (every where) and then restore and recompile the whole project.

**Comment by mohammad68a** [comment]
When I fill all optional parameters worked sounds good. but I have to fill all of the entry parameters to disappear errors. I don't think so this issue is related to specific folder because I catch this error on every project.
thank you for your attention.

**Comment by VahidN** [comment]
Compile your project and then post its output here with all of the error and warnings.

**Comment by mohammad68a** [comment]
Here you are
![image](https://user-images.githubusercontent.com/25847545/70860383-4edca700-1f36-11ea-9966-312527d6c375.png)

**Comment by VahidN** [comment]
This is by design and it's not related to this library. [More info](https://stackoverflow.com/a/46689171/298573)
