### ISSUE TITLE
Problem with padding left in IsValidIranianNationalCode method

### ISSUE THREAD

**Issue by mo-esmp** [VahidN/DNTPersianUtils.Core#21]
Validating `123456789` string with `IsValidIranianNationalCode` returns `true`! 

If input string length is not equal with 10 then you pad string from left with `0` to make string length 10 and it cause unexpected behavior in my option. If user intentionally enters  `123456789`  to avoid enter actual national code (hence it's common input) then validation will passed.

**Comment by VahidN** [comment]
My national code without its `00` at the beginning is 8 chars long. [Here are more tests](https://github.com/VahidN/DNTPersianUtils.Core/blob/master/src/DNTPersianUtils.Core.Tests/NationalCodeUtilsTests.cs#L91).

**Comment by mo-esmp** [comment]
It seems my expectation about national code length is wrong.
