### ISSUE TITLE
استفاده از این نرم افزار شما برای تبدیل تاریخ سیستم به شمسی 

### ISSUE THREAD

**Issue by ghshirdel** [VahidN/DNTPersianUtils.Core#24]
# Summary of the issue

## Environment

```
DNTPersianUtils.Core version: 
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by ghshirdel** [comment]
datetime من در مدل ها تاریخ رو از نوع 
معرفی کرده ام ولی نمیدون چکار کنم که سیستم تاریخ رو به شمسی تبدیل کنه از آیا ار این نرم افزار شما میشه برای این موضوع استفاده کرد

**Comment by VahidN** [comment]
Try
```C#
Thread.CurrentThread.CurrentCulture = PersianCulture.Instance;
```
