### ISSUE TITLE
بروز رسانی تعطیلات رسمی

### ISSUE THREAD

**Issue by mhmsignin** [VahidN/DNTPersianUtils.Core#29]
با سلام و خسته نباشی
تشکر از این ابزار مفیدت واقعا کا راه اندازه
جسارتن میخواستم بدونم لیست تعطیلات رسمی آپدیت شده برا سال 99 یا خیر.
سپاسگزارم

**Comment by VahidN** [comment]
<div dir="rtl">

[سلام؛ بله](https://github.com/VahidN/DNTPersianUtils.Core/blob/master/src/DNTPersianUtils.Core/IranHolidays.cs)
