### ISSUE TITLE
'DNTPersianUtils.Core.DateTimeUtils' exception on macOs and Docker

### ISSUE THREAD

**Issue by saeedmsdi** [VahidN/DNTPersianUtils.Core#3]
Hi

When I use this repo on my project or use your IdentityCore project on macOs or Docker I have this error : 
`fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The type initializer for 'DNTPersianUtils.Core.DateTimeUtils' threw an exception.
System.TypeInitializationException: The type initializer for 'DNTPersianUtils.Core.DateTimeUtils' threw an exception. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at DNTPersianUtils.Core.DateTimeUtils..cctor()
   --- End of inner exception stack trace ---
   at DNTPersianUtils.Core.DateTimeUtils.GetDateTimeOffsetPart(DateTimeOffset dateTimeOffset, DateTimeOffsetPart dataDateTimeOffsetPart)
   at AspNetCore._Views_SystemLog_Index_cshtml.<ExecuteAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()`

**Comment by VahidN** [comment]
Can you run this piece of code on MacOS?
```csharp
var info = TimeZoneInfo.GetSystemTimeZones().First(timeZoneInfo => timeZoneInfo.StandardName.Contains("Iran"));
```

**Comment by saeedmsdi** [comment]
No I can't. I'd test all possible things, even with System.TimeZoneInfo.GetSystemTimeZones().ToList() I have nothing on debug and log ... Nothing not null!

**Comment by VahidN** [comment]
OK. You should report it here: https://github.com/dotnet/coreclr/issues

**Comment by saeedmsdi** [comment]
@VahidN I test again on docker and osx with this piece of code : 

`foreach (TimeZoneInfo z in TimeZoneInfo.GetSystemTimeZones())
            {
                if (z.Id.Equals("Asia/Tehran"))
                {
                    Console.WriteLine(z.StandardName + " - " + z.Id);
                }
            }`

on Docker I have : 
`GMT+03:30 - Asia/Tehran` 

on osx : 
`Iran Standard Time - Asia/Tehran`

On docker I have an exception about .First(timeZoneInfo => ...) like I said before, but when I use foreach and use TimeZoneInfo.Id = "Asia/Tehran" instead of StandardName it works fine!

**Comment by VahidN** [comment]
How about this code?
```
var info = TimeZoneInfo.GetSystemTimeZones()
.First(timeZoneInfo => timeZoneInfo.StandardName.Contains("Iran") || 
timeZoneInfo.StandardName.Contains("Tehran"));
```

**Comment by saeedmsdi** [comment]
Works on both 👍

**Comment by VahidN** [comment]
Good. Thanks. Fixed via https://github.com/VahidN/DNTPersianUtils.Core/commit/f6ebdeed5a968e271c11c7f6fed87b7e71728c07
```
PM> update-package
```
