### ISSUE TITLE
مشکل اعداد به حروف

### ISSUE THREAD

**Issue by mehran282** [VahidN/DNTPersianUtils.Core#30]
# Summary of the issue

مشکل اعداد به حروف

## Environment

```
DNTPersianUtils.Core version: 3.6.8
.NET Core SDK version: 5.0
IDE: vs
```

## Example code/Steps to reproduce:
![image](https://user-images.githubusercontent.com/29571048/99886111-4107c980-2c4f-11eb-9e5f-387e6166b47c.png)

## Output:

```
Exception message: عدد بیشتر از میلیارد مدیریت نشده
نمونه تصویر ارسال شد
Full Stack trace:
```

**Comment by VahidN** [comment]
Improved it via #https://github.com/VahidN/DNTPersianUtils.Core/commit/619e23a7f797b91606e149e25c051efc6d6fc5fb
