### ISSUE TITLE
Ignore whiteSpaces in ContainsOnlyFarsiLetters

### ISSUE THREAD

**Issue by uthmanrahimi** [VahidN/DNTPersianUtils.Core#35]
I tried to use the `ContainsOnlyFarsiLetters` method to check if the user's name is completely `Farsi` but I find out that when the string contains whitespaces, this method just returns `false` (actually it does its job correctly).
I thought about expanding this method by adding an optional parameter to ignore whitespaces or not.

Thank you.

**Comment by VahidN** [comment]
Added it via#https://github.com/VahidN/DNTPersianUtils.Core/commit/9b996a9c48a58d28baff02a87742db15d9876387
