### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by mammadkoma** [VahidN/DNTPersianUtils.Core#4]
Hi Sir VahidN
We installed DNTPersianUtils.Core by nuget in VS2015.
But your persian extension methods not shows in vs intellicense.

**Comment by VahidN** [comment]
What is your selected framework version?
This library support the following versions:
![dntp](https://user-images.githubusercontent.com/766010/29302731-ee280222-819b-11e7-997a-55686c87a878.png)

**Comment by VahidN** [comment]
Tip
---
To activate the intellisense you should add the related namespace first:
```csharp
using DNTPersianUtils.Core;
```

**Comment by mammadkoma** [comment]
Yes
using DNTPersianUtils.Core;
Thanks you
