### ISSUE TITLE
مشکل با اعداد فارسی در سنجش درستی شماره شبا و شماره کارت

### ISSUE THREAD

**Issue by shedayat** [VahidN/DNTPersianUtils.Core#40]
بررسی شماره شبا و شماره کارت و... برای اعداد فارسی کار نمی کنه.

**Comment by VahidN** [comment]
<div dir="rtl">

در ابتدا از متد [ToEnglishNumbers](https://github.com/VahidN/DNTPersianUtils.Core/blob/a19320b3ff2ed36c144dbd54d8d6cb76ccd30c46/src/DNTPersianUtils.Core/PersianNumbersUtils.cs#L123) استفاده كنيد

**Comment by shedayat** [comment]
منظورم استفاده از attribute هست.

**Comment by VahidN** [comment]
Try V4.2.1

**Comment by shedayat** [comment]
آپدیت هم کردم ولی مشکل حل نشد!

**Comment by VahidN** [comment]
<div dir="rtl">

هميشه سعي كنيد زمانيكه مشكلي را مطرح مي‌كنيد يك مثال قابل بررسي هم ارائه كنيد
