### ISSUE TITLE
نسخه .net framework

### ISSUE THREAD

**Issue by AminMhmdi** [VahidN/DNTPersianUtils.Core#44]
سلام
من این نسخه رو پورت کردم برای دات نت 4.7.2
مشکلی نداره در github خودم پابلیشش کنم؟

**Comment by VahidN** [comment]
<div dir="rtl">

سلام؛ نيازي نيست. اين پروژه [مالتي تارگت](https://github.com/VahidN/DNTPersianUtils.Core/blob/master/src/DNTPersianUtils.Core/DNTPersianUtils.Core.csproj#L6) هست و از دات نت 4.6 به بالا را پشتيباني مي‌كند. بسته‌ي نيوگت آن‌را استفاده كنيد.
