### ISSUE TITLE
اضافه کردن روز هفته

### ISSUE THREAD

**Issue by Mohammad-DH** [VahidN/DNTPersianUtils.Core#49]
خسته نباشی وحید جان 
لطفا قابلیت گرفتن روز هفته به صورت جدا را اضافه کن

از وقتی که برای نوشتن این پکیج گزاشتی ممنونم 
روز خوبی داشته باشی

**Comment by VahidN** [comment]
يكسري موارد [اينجا هست](https://github.com/VahidN/DNTPersianUtils.Core/blob/master/src/DNTPersianUtils.Core/PersianCulture.cs#L18). بررسي كنيد كافي است يا مورد خاص ديگري مدنظر است؟

**Comment by Mohammad-DH** [comment]
خیلی ممنون 
مشکلم حل شد
بخاطر جواب سریعتون ممنونم
