### ISSUE TITLE
سال خاتمه ی مناسبت ها، سال 1400 است 

### ISSUE THREAD

**Issue by SomayeEbrahimi** [VahidN/DNTPersianUtils.Core#50]
# Summary of the issue

من با استفاده از متد زیر، میخوام سال خاتمه تعریف مناسبت ها در این کتابخانه رو بدوم، با وجود اینکه مناسبت های سال 1401 تعریف شده ولی این متد همچنان سال 1400 رو برمیگردونه.

## Example code:
IranHolidays.EndYear

## Output:
1400

**Comment by VahidN** [comment]
Try V 5.4.2
