### ISSUE TITLE
غلط املایی در فایل IranHolidays

### ISSUE THREAD

**Issue by MohammadRoshani** [VahidN/DNTPersianUtils.Core#58]
# Summary of the issue
کلمات "عیدنوروز" و "ولادت حضرت قائم (عج لا...)" غلط املایی هستند

**Comment by VahidN** [comment]
نمي‌دونم! شايد اينطوري هست!

https://github.com/VahidN/DNTPersianUtils.Core/commit/dab09db818a3858aa1606d2ab57c505f97f90ca2
