### ISSUE TITLE
 تایم زون صحیح ایران در ToFriendlyPersianDateTextify

### ISSUE THREAD

**Issue by dashti011** [VahidN/DNTPersianUtils.Core#62]
# Summary of the issue

با سلام و احترام
بنظر میرسه در تابع ToFriendlyPersianDateTextify تایم زون ایران با مقدار +04:30 تبدیل میشه
 مثلا ساعت ورودی 12:37:01 PM
  13:37 ولی مقدار خروجی 
نمایش داده میشه
## Environment

```
DNTPersianUtils.Core version: 
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

var outP=DateTimeReceived.ToFriendlyPersianDateTextify();

## Output:

DateTimeReceived= Sunday, April 9, 2023 12:37:01 PM

outP= ‫۱۵ روز قبل، یکشنبه ۲۰ فروردین ۱۴۰۲، ساعت ۱۳:۳۷

**Comment by VahidN** [comment]
اين اطلاعات از سيستم عامل خوانده مي‌شوند. [بايد آن‌را در سيستم عامل غيرفعال كنيد.](https://www.dntips.ir/post/1033/%d8%a7%d8%b5%d9%84%d8%a7%d8%ad-daylight-saving-time-%d9%88%db%8c%d9%86%d8%af%d9%88%d8%b2-%d8%aa%d8%a7-90-%d8%b3%d8%a7%d9%84-%d8%a8%d8%b9%d8%af#comment-18802)

**Comment by dashti011** [comment]
با سلام مجدد طبق لینک موجود در نظرات سایت فایل https://www.dntips.ir/file/userfile?name=disable_daylight_saving_time.zip را دانلود و اجرا کردم و سرور رو ریستارت ، اما مشکل فوق حل نشد.
همچنین که در حال حاضر در کامپیوتر مد نظر با سیستم عامل ویندوز 10 گزینه daylight saving  هم خاموش بوده و ساعت سیستم مطابق ساعت صحیح نمایش فعلی ایران نمایش داده میشه.

**Comment by VahidN** [comment]
پارامتر convertToIranTimeZone را با false مقدار دهي كنيد.

**Comment by dashti011** [comment]
طبق بررسی اولیه ای که انجام دادم ،به یک نکته رسیدم 
در حال حاضر این کتابخانه را از طریق NUGet  آخرین نسخه فعلی اون یعنی 5.6.0 رو دانلود و نصب کردم و امروز 2023/04/25 هم به اخرین نسخه بروزرسانی کردم
برای بررسی سورس را هم از گیت هاب دانلود کردم ,  و متوجه شدم در سورس فعلی موجود در گیت ها پارامتر convertToIranTimeZone وجود دارد در صورتی که از بسته دانلودی از Nuget  با نسخه 5.6.0 این پارامتر وجود ندارد 

https://github.com/VahidN/DNTPersianUtils.Core/blob/27283423f9839c04b3d47e84a5c4a3511d2c60fc/src/DNTPersianUtils.Core/FriendlyPersianDateUtils.cs#L136

https://github.com/VahidN/DNTPersianUtils.Core/blob/27283423f9839c04b3d47e84a5c4a3511d2c60fc/src/DNTPersianUtils.Core/FriendlyPersianDateUtils.cs#L97

**Comment by VahidN** [comment]
- [خروجي اين كتابخانه و ارسال آن به Nuget خودكار هست و بدون دخالت شخصي](https://github.com/VahidN/DNTPersianUtils.Core/blob/master/.github/workflows/build.yml#L24)
- بسته‌ي نهايي را از NuGet دريافت و با استفاده از ILSpy هم بررسي كردم. مشكلي نبود.

**Comment by dashti011** [comment]
ممنون بابت پاسخگویی و زمانی گذاشتید ، متوجه اشکال کارم شدم .
 چون نوع زمان ورودی من بر اساس DateTimeOffset بود و پارامتر convertToIranTimeZone  برای ورودی های DateTime  بود که با تبدیل ورودی از DateTimeOffset  به DateTime  مشکل حل شد.

**Comment by davardoust** [comment]
سلام. ما هم این مشکل رو داریم. ساعت سرور هم از نظر daylightsaving درست است. نمیخوایم DateTimeOffset را به DateTime تبدیل کنیم. آیا راه دیگری وجود دارد؟

**Comment by dashti011** [comment]
> سلام. ما هم این مشکل رو داریم. ساعت سرور هم از نظر daylightsaving درست است. نمیخوایم DateTimeOffset را به DateTime تبدیل کنیم. آیا راه دیگری وجود دارد؟

یکی از راه حل های کوتاه تر و ساده تر که ما انجام دادیم ([لینک اصلی](https://learn.microsoft.com/en-us/dotnet/standard/datetime/converting-between-datetime-and-offset#conversions-from-datetimeoffset-to-datetime))، در نهایت از متغیری که DateTimeOffset  بود با دستور
 DateTimeOffset .DateTime  
در لحظه **نمایش** اونو به DateTime  تبدیل کردیم. البته که روش ها بسیاری برای این کار هست ولی ساده ترین اونو بدون نیاز به تغییر در سورس اصلی ، روش  گفته شده بود.

**Comment by VahidN** [comment]
مشكل اصلي اينجا است كه هر چند پچ ارائه شده به ظاهر UTC-offset را 3:30 مي‌كند، اما اجزاي تنظيمي آن هنوز هم daylight saving time را به رسميت مي‌شناسد و بر اين اساس اطلاعات را اصلاح مي‌كند:
![dtIran](https://user-images.githubusercontent.com/766010/234513408-03512901-2b05-49bd-a268-d5f66cc4493a.png)

يعني خروجي نهايي زير هنوز هم بر اساس 4:30 محاسبه مي‌شود و نه 3:30:

```C#
    var dateTime = DateTimeOffset.UtcNow;
    var iranTime = TimeZoneInfo.ConvertTime(dateTime, iranStandardTime);
    Console.WriteLine(iranTime); // 06/02/1402 12:34:23 ?.? +04:30
```

با بايد مايكروسافت اين مشكل را با يك به روز رساني حل كند و يا خودمان آن‌را پچ كنيم.

**Comment by skhm89** [comment]
> مشكل اصلي اينجا است كه هر چند پچ ارائه شده به ظاهر UTC-offset را 3:30 مي‌كند، اما اجزاي تنظيمي آن (adjustment rules) هنوز هم daylight saving time را به رسميت مي‌شناسد و بر اين اساس اطلاعات را اصلاح مي‌كند: ![dtIran](https://user-images.githubusercontent.com/766010/234513408-03512901-2b05-49bd-a268-d5f66cc4493a.png)
> 
> يعني خروجي نهايي زير هنوز هم بر اساس 4:30 محاسبه مي‌شود و نه 3:30:
> 
> ```cs
>     var iranStandardTime = TimeZoneInfo.GetSystemTimeZones()
>                                        .FirstOrDefault(timeZoneInfo =>
>                                                            timeZoneInfo.StandardName.Contains("Iran",
>                                                             StringComparison.OrdinalIgnoreCase));
>     Console.WriteLine(iranStandardTime.BaseUtcOffset); // 03:30:00
> 
>     var dateTime = DateTimeOffset.UtcNow;
>     var iranTime = TimeZoneInfo.ConvertTime(dateTime, iranStandardTime);
>     Console.WriteLine(iranTime); // 06/02/1402 12:34:23 ?.? +04:30
> ```
> 
> يا بايد مايكروسافت اين مشكل را با يك به روز رساني حل كند (بايد adjustment rules را اصلاح كند) و يا خودمان آن‌را پچ كنيم.

جناب نصیری سلام
بعید میدونم مایکروسافت به این زودی مشکل رو حل کنه، اگه مقدور هست خودتون زحمتشو بکشید.
ضمن اینکه در کتابخانه زمانبندی و نمایش وضعیت جاب های در حال اجرا (ScheduledTaskStatus) این مشکل وجود داره.

**Comment by VahidN** [comment]
[روش رفع مشكل](https://www.dntips.ir/post/3476/%d8%b1%d9%81%d8%b9-%d9%85%d8%b4%da%a9%d9%84-%d8%aa%d8%a8%d8%af%db%8c%d9%84%d8%a7%d8%aa-utc-%d8%a8%d8%a7-%d8%aa%d8%ba%db%8c%db%8c%d8%b1-%d8%a7%d8%b7%d9%84%d8%a7%d8%b9%d8%a7%d8%aa-timezone-%d8%a7%db%8c%d8%b1%d8%a7%d9%86-%d8%af%d8%b1-%d9%88%db%8c%d9%86%d8%af%d9%88%d8%b2)
