### ISSUE TITLE
تعطیلات ناگهانی

### ISSUE THREAD

**Issue by MehdiZohrevnd** [VahidN/DNTPersianUtils.Core#65]
# Summary of the issue
 آیا این کتابخانه قابلیت تشخیص تعطیلات ناگهانی هم داره ؟ مثلا امروز آیت الله صافی گلپایگانی به رحمت خدا بره و دولت 2 روز تعطیلی اعلام کنه ؟
یا مثلا امروز کرونا شیوع پیدا کنه ، ناگهانی اعلام کنن فردا همه ی ادارات دنیا تعطیه ؟

## Environment

```
DNTPersianUtils.Core version: 
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
در صورت وقوع، ناگهاني‌ها، تبديل به رسمي و قطعي شده و در برنامه انعكاس پيدا خواهند كرد.
