### ISSUE TITLE
تفاوت خروجی تبدیل ایران سیستم به یونی کد و یونی کد به ایران سیستم

### ISSUE THREAD

**Issue by SoltaniSepehr** [VahidN/DNTPersianUtils.Core#66]
هنگامی که نمونه فایل دیسک بیمه تامین اجتماعی را به فونت فارسی تبدیل میکنیم خروجی درستی داریم. اما زمانی که همان متن تبدیل شده را به یونی کد تبدیل میکنیم در بعضی کارکرتها دچار مشکل میشود و برگردان یونی کد ساخاه شده توسط همین به پکیج به فارسی درست نمیباشد
مشکل این است که در هنگام تبدیل یونی کد به ایران سیستم تابع  FromUnicodeToIranSystem پارامتر دومی قبول میکند که در آن ArbicContext  قرار میگیرد و ترجمه درست انجام میشود.
اما در تبدیل  ایران سیستم به یونی کد  FromIranSystemToUnicode این پارامتر دوم موجود نیست

**Comment by VahidN** [comment]
لطفا يك نمونه مثال ارسال كنيد.

**Comment by VahidN** [comment]
Added it via#https://github.com/VahidN/DNTPersianUtils.Core/commit/a05df054834da236ddca788c7bbfde7c0fa6a4b4
