### ISSUE TITLE
خطا هنگام پابلیش و انتشار 

### ISSUE THREAD

**Issue by mahdisys** [VahidN/DNTPersianUtils.Core#67]
# Summary of the issue

هنگام انتشار اپلیکیشن از طریق iis publish profile  در ویژوال استودیو ددقیقا زمانی ارور تایم اوت کانکشن ممیده که نوبت به انتشار فایل dll پکیج DNTPersianUtilsCore.ddl میشه 

## Environment
Release
```
DNTPersianUtils.Core version: 
5.7.1
.NET Core SDK version: 
6.0
IDE: 
```
VisualStudio 2022
## Example code/Steps to reproduce:

```
paste your core code
```

## Output:
C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(140,5): Warning : Retrying the sync because a socket error (10054) occurred.  
```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
[ارتباطي به اين پروژه ندارد.](https://stackoverflow.com/questions/29696898/vs-to-azure-publish-failure-socket-error-10054)
