### ISSUE TITLE
Customize ToFriendlyPersianDateTextify 

### ISSUE THREAD

**Issue by daliri72** [VahidN/DNTPersianUtils.Core#7]
I Have DateTime type and It type has English DateTime. I would like to use ToFriendlyPersianDateTextify but I don't want to return time. just return like `‫۱۰ روز قبل، سه شنبه ۲۱ دی ۱۳۹۵`
How can I use it?

**Comment by VahidN** [comment]
Added via #https://github.com/VahidN/DNTPersianUtils.Core/commit/8ba80b5df0e78d58d824799c4a6e576feb50bdb6
