### ISSUE TITLE
error in convert datetime

### ISSUE THREAD

**Issue by mehran2822** [VahidN/DNTPersianUtils.Core#70]
# Summary of the issue

## Environment

```
DNTPersianUtils.Core version: 8
.NET Core SDK version: 8
IDE: visual studio 17.3
```

## Example code/Steps to reproduce:

```
paste your core code
```
 CurrentTimePersianString = DateTime.Now.ToPersianDateTextify(),
 CurrentTimePersianFreindlyString = DateTime.Now.ToFriendlyPersianDateTextify(),

## Output:

```
Exception message:
Full Stack trace:
```
![image](https://github.com/VahidN/DNTPersianUtils.Core/assets/154413537/f22f5eb0-8d9d-4981-9421-1dd58e9a56d9)

**Comment by VahidN** [comment]
لطفا به فارسي توضيح دهيد كه دقيقا مشغول به چه‌كاري و در چه محيطي و چه برنامه‌اي بوديد كه اين خطا را مشاهده كرديد؟

**Comment by VahidN** [comment]
همچنين اگر در پروژه‌ي خود چنين تنظيمي را در مورد InvariantGlobalization داريد، آن‌را false كنيد:
```xml
 <PropertyGroup>
   <TargetFramework>net8.0</TargetFramework>
   <Nullable>enable</Nullable>
   <ImplicitUsings>enable</ImplicitUsings>
   <InvariantGlobalization>false</InvariantGlobalization>
 </PropertyGroup>
```
