### ISSUE TITLE
I can't use it with anonymous objects!?

### ISSUE THREAD

**Issue by RGitHuben** [VahidN/DNTPersianUtils.Core#71]
# Summary of the issue
An expression tree may not contain a call or invocation that uses optional arguments
 
## Environment
MVC
DNTPersianUtils.Core version: 
.NET Core SDK version: 8
IDE: Visual Studio
 
## Example code/Steps to reproduce:

```
paste your core code
Foo.Select(i => new{
                    i.Id,
                    i.Name, 
                    i.CreatedDate,
                    CreatedDateFa = i.CreatedDate.ToFriendlyPersianDateTextify()
                  });
 I have a solution that requires some coding like 
  private static string ToPersianFirendly(DateTime dt)
  {
      return dt.ToFriendlyPersianDateTextify(); 
  }
and then use it in anonymous object:
Foo.Select(i =>new {
CreatedDateFa = ToPersianFirendly(i.CreatedDate)
})
## Output:

```
Exception message:
Full Stack trace:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0854	An expression tree may not contain a call or invocation that uses optional arguments

**Comment by VahidN** [comment]
`ToFriendlyPersianDateTextify()` method has some `optional` parameters and you have to provide them explicitly in your case.
