### ISSUE TITLE
استفاده از متدهای به صورت فیلتر

### ISSUE THREAD

**Issue by mohammadhosseinzavvar** [VahidN/DNTPersianUtils.Core#72]
سلام
چطور میشه در دات نت کر متد های ApplyCorrectYeKe یا ToEnglishNumbers و به صورت فیلتر استفاده کرد که به طور خودکار روی تمام ورودی ها اعمال شود ؟
```
DNTPersianUtils.Core version: 5.9
.NET Core SDK version: .Net Core 8.0.2
IDE: 
```

**Comment by VahidN** [comment]
[به اين صورت](https://github.com/search?q=repo%3AVahidN%2FDNTCommon.Web.Core%20ApplyCorrectYeKeFilter&type=code)
