### ISSUE TITLE
مناسبت ها

### ISSUE THREAD

**Issue by ghost1372** [VahidN/DNTPersianUtils.Core#9]
سلام لطفا مناسبت ها رو هم اضافه کنید

**Comment by VahidN** [comment]
<div dir="rtl">
سلام؛ با توجه به متغير بودن اين مساله، مرسوم نيست چنين اطلاعاتي را در يك كتابخانه قرار دهند

**Comment by ghost1372** [comment]
بله ولی منظورم پیاده سازی متدی بود تا برنامه نویس توسط اون بتونه فایل مناسبت ها رو در قالب های مختلف حالا جیسون یا sqlite
به برنامش معرفی کنه و باقی کارو کتابخونه انجام بده

**Comment by VahidN** [comment]
Added via #https://github.com/VahidN/DNTPersianUtils.Core/commit/b6e2fdc7fb203602398f9f781ec132766e3f89d1
